# -*- coding: utf-8 -*-
"""Agenda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vhOurgFgyZmtJjax78xqokEZp6vv5yZq
"""

import json

agenda = []

def salvar_agenda():
    with open('agenda.json', 'w') as arquivo:
        json.dump(agenda, arquivo)
        print("Agenda salva com sucesso!")

def carregar_agenda():
    try:
        with open('agenda.json', 'r') as arquivo:
            agenda_carregada = json.load(arquivo)
            print("Agenda carregada com sucesso!")
            return agenda_carregada
    except:
        print("Nenhuma agenda encontrada.")
        return []

def adicionar_contato(nome, telefone, email):
    contato = {
        'nome': nome,
        'telefone': telefone,
        'email': email
    }
    agenda.append(contato)

def exibir_agenda():
    print("\nLista de contatos:")
    if not agenda:
        print("A agenda está vazia.")
    else:
        for contato in agenda:
            print("Nome:", contato['nome'])
            print("Telefone:", contato['telefone'])
            print("E-mail:", contato['email'])

def editar_contato():
    nome = input("Digite o nome do contato que deseja editar: ")
    for contato in agenda:
        if contato['nome'] == nome:
            contato['telefone'] = input("Digite o novo telefone: ")
            contato['email'] = input("Digite o novo e-mail: ")
            print("Contato editado com sucesso!\n")
            return
    print("Contato não encontrado.\n")

def remover_contato():
    nome = input("Digite o nome do contato que deseja remover: ")
    for contato in agenda:
        if contato['nome'] == nome:
            agenda.remove(contato)
            print("Contato removido com sucesso!\n")
            return
    print("Contato não encontrado.\n")

# Carrega a agenda ao iniciar
agenda = carregar_agenda()

# Loop principal do menu
while True:
    print("\n-- Menu da Agenda")
    print("1. Inserir um contato")
    print("2. Exibir Agenda")
    print("3. Editar contato")
    print("4. Remover contato")
    print("5. Salvar agenda")
    print("6. Sair")

    opcao = input("Digite a opção desejada: ")

    if opcao == "1":
        print("\nInserir um contato:")
        nome = input("Digite o nome do contato: ")
        telefone = input("Digite o telefone do contato: ")
        email = input("Digite o e-mail do contato: ")
        adicionar_contato(nome, telefone, email)
        print("Contato adicionado com sucesso!\n")

    elif opcao == "2":
        exibir_agenda()

    elif opcao == "3":
        editar_contato()

    elif opcao == "4":
        remover_contato()

    elif opcao == "5":
        salvar_agenda()

    elif opcao == "6":
        print("Saindo...")
        break

    else:
        print("Opção inválida. Digite um número de 1 a 6.")